version: "3.7"
services:
  web:
    build: apache\
    volumes:
      - .\apache\httpdocs:/var/www/html
      - .\apache\logs:/var/log/apache2
    ports:
      - 8080:80
    environment: 
      NETTE_DEBUG: "HslWZy4PjYRSBoa9F718"
  db:
    image: mysql
    volumes:
      - .\mysql\data:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on: 
      - db
    ports: 
      - 8081:80
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret